version: '2.2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${EZ_AF_USER}
            - POSTGRES_PASSWORD=${EZ_AF_PASSWORD}
            - POSTGRES_DB=airflow
        ports:
            - "5430:5432"

    rserver:
        build:
            context: ./rserver
        command: >
            /bin/bash -c "
                service ssh start
                sleep infinity
            "

    pythonserver:
        build:
            context: ./pythonserver
        command: >
            /bin/bash -c "
                service ssh start
                sleep infinity
            "

    airflow:
        build:
            context: .
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${EZ_AF_META_DB}
            - EZ_AF_PYTHON_SERVER=${EZ_AF_PYTHON_SERVER}
            - EZ_AF_R_SERVER=${EZ_AF_R_SERVER}
        command: >
            /bin/bash -c "
                # Wait for PG
                sleep 5

                # Sending over RSA keys
                sshpass -p ${EZ_AF_PASSWORD} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ${EZ_AF_USER}@${EZ_AF_PYTHON_SERVER}
            	sshpass -p ${EZ_AF_PASSWORD} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no ${EZ_AF_USER}@${EZ_AF_R_SERVER}

                # Clean up pid
                rm -f airflow-webserver.pid

                #Not currently using makefiles make airflow_init
                airflow upgradedb
            	airflow variables -s EZ_AF_USER ${EZ_AF_USER}
            	airflow connections -a --conn_id postgres_datalake --conn_uri ${EZ_AF_DATALAKE}
            	python3 setup_views.py

                #Not currently using makefiles airflow_up
                airflow scheduler &
            	airflow webserver

                # Keep the server on no matter what
                sleep infinity
            "
        restart: always
        depends_on:
            - postgres
            - pythonserver
            - rserver
        volumes:
            - ./airflow:/usr/local/airflow
        ports:
            - "8080:8080"
