# taken from...
# https://raw.githubusercontent.com/puckel/docker-airflow/master/docker-compose-LocalExecutor.yml
version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5430:5432"

    rserver:
        build:
            context: ./rserver
        environment:
            - PASSWORD=rstudio_password
        ports:
            - "8787:8787"
        volumes:
            - ./airflow:/usr/local/airflow

    pythonserver:
        build:
            context: ./pythonserver
        command: >
            /bin/bash -c "
                service ssh start
                sleep infinity
            "
        ports:
            - "8888:8888"
        volumes:
            - ./airflow:/usr/local/airflow

    airflow:
        build:
            context: .
        command: >
            /bin/bash -c "
                sleep 10;
                make airflow_init airflow_up;
            "
        environment:
            - AIRFLOW_CONN_SSH_PYTHONSERVER=ssh://pythonuser:pass@pythonserver:22
            - AIRFLOW_CONN_SSH_RSERVER=ssh://rstudio:rstudio_password@rserver:22
        restart: always
        depends_on:
            - postgres
        volumes:
            - ./airflow:/usr/local/airflow
        ports:
            - "8080:8080"
