version: '3.3'
services:
  postgres:
    image: postgres:13.1
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DEFAULT_USER}
      - POSTGRES_PASSWORD=${DEFAULT_PASSWORD}
      - POSTGRES_DB=meltano
    ports:
      - "5678:5432"
  meltano:
    image: meltano/meltano:latest-python3.8
    depends_on:
      - postgres
    volumes:
      - .:/usr/local/share/cfp
    ports:
      - "5000:5000"
    working_dir: /usr/local/share/cfp/meltano/cfp-pipeline
