version: '2.2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${GUSTY_USER}
            - POSTGRES_PASSWORD=${GUSTY_PASSWORD}
            - POSTGRES_DB=airflow
        ports:
            - "5430:5432"

    rserver:
        build:
            context: ./rserver
        command: >
            /bin/bash -c "
                service ssh start
                sleep infinity
            "

    pythonserver:
        build:
            context: ./pythonserver
        command: >
            /bin/bash -c "
                service ssh start
                sleep infinity
            "

    airflow:
        build:
            context: .
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://${GUSTY_USER}:${GUSTY_PASSWORD}@postgres:5432/airflow
            - AIRFLOW_CONN_POSTGRES_DEFAULT=postgresql://${GUSTY_USER}:${GUSTY_PASSWORD}@postgres:5432/datalake
            - AIRFLOW_CONN_PYTHONSERVER_DEFAULT=ssh://${GUSTY_USER}:${GUSTY_PASSWORD}@pythonserver?no_host_key_check=true
            - AIRFLOW_CONN_RSERVER_DEFAULT=ssh://${GUSTY_USER}:${GUSTY_PASSWORD}@rserver?no_host_key_check=true
        command: >
            /bin/bash -c "
                # Wait for PG
                sleep 5

                # Install gusty (while in development)
                # pip uninstall -y gusty
                # pip install --upgrade git+git://github.com/chriscardillo/gusty

                # Clean up pid
                rm -f airflow-webserver.pid

                airflow upgradedb
            	airflow variables -s GUSTY_USER ${GUSTY_USER}
            	python3 setup_views.py

                airflow scheduler &
            	airflow webserver

                # Keep the server on no matter what
                sleep infinity
            "
        restart: always
        depends_on:
            - postgres
            - pythonserver
            - rserver
        volumes:
            - ./airflow:/usr/local/airflow
        ports:
            - "8080:8080"
