# This is a basic workflow to help you get started with Actions

name: Update Repos for Meltano

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Get projects/repos from brigade.cloud
        run: |
          python scripts/parse_repo_json.py

      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.5.0
        with:
          commit-msg: "Updating list of github repositories in meltano.yml from github action"
          # Path to file(s) or glob pattern
          file-path: meltano/cfp-pipeline/meltano.yml # optional

          github-token:  ${{ secrets.GITHUB_TOKEN }} # optional
          allow-removing: false # optional
          branch: staging
