# This is a basic workflow to help you get started with Actions

name: Update Repos for Meltano

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            NEW_REPOS=`curl https://brigade.cloud/static-api/v1/organizations/Code%20for%20Philly/projects.json | python3 scripts/parse_repo_json.py`
            sed -i "s,repository:.*,repository: $NEW_REPOS," meltano/cfp-pipeline/meltano.yml
          
      - name: Update files on GitHub
        # You may pin to the exact commit or the version.
        # uses: test-room-7/action-update-file@eb359a156419371010bcda984013cfb66b887c6d
        uses: test-room-7/action-update-file@v1.5.0
        with:
          # Commit message
          commit-msg: "Auto Commit" # optional
          # Path to file(s) or glob pattern
          file-path: meltano/cfp-pipeline/meltano.yml # optional
          github-token:  ${{ secrets.GITHUB_TOKEN }} # optional
          allow-removing: false # optional
          branch: staging
